export default {
	// Clipboard Events
	'copy': 'copy',
	'copycapture': 'copyCapture',
	'cut': 'cut',
	'cutcapture': 'cutCapture',
	'paste': 'paste',
	'pastecapture': 'pasteCapture',

	// Composition Events
	'compositionend': 'compositionEnd',
	'compositionendcapture': 'compositionEndCapture',
	'compositionstart': 'compositionStart',
	'compositionstartcapture': 'compositionStartCapture',
	'compositionupdate': 'compositionUpdate',
	'compositionupdatecapture': 'compositionUpdateCapture',

	// Focus Events
	'focus': 'focus',
	'focuscapture': 'focusCapture',
	'blur': 'blur',
	'blurcapture': 'blurCapture',

	// Form Events
	'change': 'change',
	'changecapture': 'changeCapture',
	'beforeinput': 'beforeInput',
	'beforeinputcapture': 'beforeInputCapture',
	'input': 'input',
	'inputcapture': 'inputCapture',
	'reset': 'reset',
	'resetcapture': 'resetCapture',
	'submit': 'submit',
	'submitcapture': 'submitCapture',
	'invalid': 'invalid',
	'invalidcapture': 'invalidCapture',

	// Image Events
	'load': 'load',
	'loadcapture': 'loadCapture',
	'error': 'error',
	'errorcapture': 'errorCapture',

	// Keyboard Events
	'keydown': 'keyDown',
	'keydowncapture': 'keyDownCapture',
	'keypress': 'keyPress',
	'keypresscapture': 'keyPressCapture',
	'keyup': 'keyUp',
	'keyupcapture': 'keyUpCapture',

	// Media Events
	'abort': 'abort',
	'abortcapture': 'abortCapture',
	'canplay': 'canPlay',
	'canplaycapture': 'canPlayCapture',
	'canplaythrough': 'canPlayThrough',
	'canplaythroughcapture': 'canPlayThroughCapture',
	'durationchange': 'durationChange',
	'durationchangecapture': 'durationChangeCapture',
	'emptied': 'emptied',
	'emptiedcapture': 'emptiedCapture',
	'encrypted': 'encrypted',
	'encryptedcapture': 'encryptedCapture',
	'ended': 'ended',
	'endedcapture': 'endedCapture',
	'loadeddata': 'loadedData',
	'loadeddatacapture': 'loadedDataCapture',
	'loadedmetadata': 'loadedMetadata',
	'loadedmetadatacapture': 'loadedMetadataCapture',
	'loadstart': 'loadStart',
	'loadstartcapture': 'loadStartCapture',
	'pause': 'pause',
	'pausecapture': 'pauseCapture',
	'play': 'play',
	'playcapture': 'playCapture',
	'playing': 'playing',
	'playingcapture': 'playingCapture',
	'progress': 'progress',
	'progresscapture': 'progressCapture',
	'ratechange': 'rateChange',
	'ratechangecapture': 'rateChangeCapture',
	'resize': 'resize',
	'resizecapture': 'resizeCapture',
	'seeked': 'seeked',
	'seekedcapture': 'seekedCapture',
	'seeking': 'seeking',
	'seekingcapture': 'seekingCapture',
	'stalled': 'stalled',
	'stalledcapture': 'stalledCapture',
	'suspend': 'suspend',
	'suspendcapture': 'suspendCapture',
	'timeupdate': 'timeUpdate',
	'timeupdatecapture': 'timeUpdateCapture',
	'volumechange': 'volumeChange',
	'volumechangecapture': 'volumeChangeCapture',
	'waiting': 'waiting',
	'waitingcapture': 'waitingCapture',

	// MouseEvents
	'auxclick': 'auxClick',
	'auxclickcapture': 'auxClickCapture',
	'click': 'click',
	'clickcapture': 'clickCapture',
	'contextmenu': 'contextMenu',
	'contextmenucapture': 'contextMenuCapture',
	'doubleclick': 'doubleClick',
	'doubleclickcapture': 'doubleClickCapture',
	'drag': 'drag',
	'dragcapture': 'dragCapture',
	'dragend': 'dragEnd',
	'dragendcapture': 'dragEndCapture',
	'dragenter': 'dragEnter',
	'dragentercapture': 'dragEnterCapture',
	'dragexit': 'dragExit',
	'dragexitcapture': 'dragExitCapture',
	'dragleave': 'dragLeave',
	'dragleavecapture': 'dragLeaveCapture',
	'dragover': 'dragOver',
	'dragovercapture': 'dragOverCapture',
	'dragstart': 'dragStart',
	'dragstartcapture': 'dragStartCapture',
	'drop': 'drop',
	'dropcapture': 'dropCapture',
	'mousedown': 'mouseDown',
	'mousedowncapture': 'mouseDownCapture',
	'mouseenter': 'mouseEnter',
	'mouseleave': 'mouseLeave',
	'mousemove': 'mouseMove',
	'mousemovecapture': 'mouseMoveCapture',
	'mouseout': 'mouseOut',
	'mouseoutcapture': 'mouseOutCapture',
	'mouseover': 'mouseOver',
	'mouseovercapture': 'mouseOverCapture',
	'mouseup': 'mouseUp',
	'mouseupcapture': 'mouseUpCapture',

	// Selection Events
	'select': 'select',
	'selectcapture': 'selectCapture',

	// Touch Events
	'touchcancel': 'touchCancel',
	'touchcancelcapture': 'touchCancelCapture',
	'touchend': 'touchEnd',
	'touchendcapture': 'touchEndCapture',
	'touchmove': 'touchMove',
	'touchmovecapture': 'touchMoveCapture',
	'touchstart': 'touchStart',
	'touchstartcapture': 'touchStartCapture',

	// Pointer Events
	'pointerdown': 'pointerDown',
	'pointerdowncapture': 'pointerDownCapture',
	'pointermove': 'pointerMove',
	'pointermovecapture': 'pointerMoveCapture',
	'pointerup': 'pointerUp',
	'pointerupcapture': 'pointerUpCapture',
	'pointercancel': 'pointerCancel',
	'pointercancelcapture': 'pointerCancelCapture',
	'pointerenter': 'pointerEnter',
	'pointerentercapture': 'pointerEnterCapture',
	'pointerleave': 'pointerLeave',
	'pointerleavecapture': 'pointerLeaveCapture',
	'pointerover': 'pointerOver',
	'pointerovercapture': 'pointerOverCapture',
	'pointerout': 'pointerOut',
	'pointeroutcapture': 'pointerOutCapture',
	'gotpointercapture': 'gotPointerCapture',
	'gotpointercapturecapture': 'gotPointerCaptureCapture',
	'lostpointercapture': 'lostPointerCapture',
	'lostpointercapturecapture': 'lostPointerCaptureCapture',

	// UI Events
	'scroll': 'scroll',
	'scrollcapture': 'scrollCapture',

	// Wheel Events
	'wheel': 'wheel',
	'wheelcapture': 'wheelCapture',

	// Animation Events
	'animationstart': 'animationStart',
	'animationstartcapture': 'animationStartCapture',
	'animationend': 'animationEnd',
	'animationendcapture': 'animationEndCapture',
	'animationiteration': 'animationIteration',
	'animationiterationcapture': 'animationIterationCapture',

	// Transition Events
	'transitionend': 'transitionEnd',
	'transitionendcapture': 'transitionEndCapture',

};
